[workspace]
resolver = "2"

members = ["day-*"]

[workspace.dependencies]
miette = { version = "5.10", features = ["fancy"] }
divan = "0.1.3"
itertools = "0.12.0"
rstest = "0.18.2"
rstest_reuse = "0.6.0"
