[package]
name = "day-1"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
miette = {workspace = true}

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "day-01"
path = "benches/benchmarks.rs"
harness = false
